# SPDX-FileCopyrightText: Dom Rodriguez <shymega+toybox@shymega.org.uk>
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "rustebin"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
rocket = { version = "0.5.0-rc.3", features = ["json"] }
serde = { version = "1.0.164", features = ["derive"] }
sqlx = { version = "0.6.3", features = ["postgres", "uuid", "runtime-tokio-rustls"] }
tokio = { version = "1.29.1", features = ["full"] }
uuid = { version = "1.3.4", features = ["v4"] }
