# SPDX-FileCopyrightText: Dom Rodriguez <shymega+rustebin@shymega.org.uk>
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "rustebin"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.56.1"
aws-sdk-rds = "0.30.0"
aws-sdk-s3 = "0.30.0"
aws_lambda_events = { version = "0.10.0", default-features = false, features = ["apigw", "s3"] }
chrono = { version = "0.4.28", features = ["serde"] }
env_logger = "0.10.0"
lambda_http = { version = "0.8.1", features = ["apigw_http"] }
lambda_runtime = "0.8.2"
lazy_static = "1.4.0"
log = "0.4.20"
openssl = { version = "0.10.57", features = ["vendored"] }
rocket = { version = "0.5.0-rc.3", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
sqlx = { version = "0.7.1", features = ["postgres", "uuid", "runtime-tokio-rustls"] }
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["full"] }
uuid = { version = "1.4.1", features = ["v4"] }
